#include "dr4/converts.hpp"
#include "dr4/keycodes.hpp"
#include "dr4/mouse_buttons.hpp"
#include <SFML/Window/Event.hpp>
#include <SFML/Window/Keyboard.hpp>
#include <SFML/Window/Mouse.hpp>

sf::Mouse::Button
dr4::impl::detail::toSFML( dr4::MouseButtonType button )
{
    switch ( button )
    {
        case dr4::MouseButtonType::LEFT:
            return sf::Mouse::Left;
        case dr4::MouseButtonType::RIGHT:
            return sf::Mouse::Right;
        case dr4::MouseButtonType::MIDDLE:
            return sf::Mouse::Middle;
        default:
            return sf::Mouse::ButtonCount;
    }
}

dr4::MouseButtonType
dr4::impl::detail::fromSFML( sf::Mouse::Button button )
{
    switch ( button )
    {
        case sf::Mouse::Left:
            return dr4::MouseButtonType::LEFT;
        case sf::Mouse::Right:
            return dr4::MouseButtonType::RIGHT;
        case sf::Mouse::Middle:
            return dr4::MouseButtonType::MIDDLE;
        default:
            return dr4::MouseButtonType::UNKNOWN;
    }
}

dr4::KeyMode
dr4::impl::detail::fromSFML( sf::Event::KeyEvent event )
{
    if ( event.alt )
    {
        return dr4::KeyMode::KEYMOD_ALT;
    }

    if ( event.shift )
    {
        return dr4::KeyMode::KEYMOD_SHIFT;
    }

    if ( event.control )
    {
        return dr4::KeyMode::KEYMOD_CTRL;
    }

    return dr4::KeyMode::KEYMOD_NONE;
}

#define CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( guiType, huiType )                             \
    case sf::Keyboard::Key::guiType:                                                               \
        return dr4::KEYCODE_##huiType

dr4::KeyCode
dr4::impl::detail::fromSFML( sf::Keyboard::Key code )
{
    switch ( code )
    {
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( A, A );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( B, B );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( C, C );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( D, D );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( E, E );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F, F );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( G, G );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( H, H );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( I, I );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( J, J );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( K, K );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( L, L );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( M, M );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( N, N );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( O, O );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( P, P );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Q, Q );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( R, R );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( S, S );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( T, T );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( U, U );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( V, V );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( W, W );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( X, X );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Y, Y );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Z, Z );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Num0, NUM0 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Num1, NUM1 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Num2, NUM2 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Num3, NUM3 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Num4, NUM4 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Num5, NUM5 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Num6, NUM6 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Num7, NUM7 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Num8, NUM8 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Num9, NUM9 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Escape, ESCAPE );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( LControl, LCONTROL );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( LShift, LSHIFT );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( LAlt, LALT );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( LSystem, LSYSTEM );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( RControl, RCONTROL );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( RShift, RSHIFT );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( RAlt, RALT );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( RSystem, RSYSTEM );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Menu, MENU );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( LBracket, LBRACKET );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( RBracket, RBRACKET );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Semicolon, SEMICOLON );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Comma, COMMA );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Period, PERIOD );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Quote, QUOTE );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Slash, SLASH );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Backslash, BACKSLASH );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Tilde, TILDE );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Equal, EQUAL );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Hyphen, HYPHEN );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Space, SPACE );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Enter, ENTER );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Backspace, BACKSPACE );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Tab, TAB );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( PageUp, PAGEUP );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( PageDown, PAGEDOWN );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( End, END );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Home, HOME );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Insert, INSERT );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Delete, DELETE );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Add, ADD );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Subtract, SUBTRACT );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Multiply, MULTIPLY );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Divide, DIVIDE );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Left, LEFT );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Right, RIGHT );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Up, UP );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Down, DOWN );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Numpad0, NUMPAD0 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Numpad1, NUMPAD1 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Numpad2, NUMPAD2 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Numpad3, NUMPAD3 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Numpad4, NUMPAD4 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Numpad5, NUMPAD5 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Numpad6, NUMPAD6 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Numpad7, NUMPAD7 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Numpad8, NUMPAD8 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Numpad9, NUMPAD9 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F1, F1 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F2, F2 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F3, F3 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F4, F4 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F5, F5 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F6, F6 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F7, F7 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F8, F8 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F9, F9 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F10, F10 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F11, F11 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F12, F12 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F13, F13 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F14, F14 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( F15, F15 );
        CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY( Pause, PAUSE );
        default:
            return dr4::KEYCODE_UNKNOWN;
    }
    return dr4::KEYCODE_UNKNOWN;
}

#undef CASE_SFML_KEYBOARD_KEY_TO_DR4_KEYBOARD_KEY
